# IMPORTANT:
# This file is accessed and ignored by the program and .gitignore respectively as
# 'secret.yaml'.
# Be sure you rename this file before doing anything major!

discord:
  # Authentication token
  token: "your.discord-bots.token"
  # Application client id
  client: "0000000000000000000"

  admin:
    my_username: "0000000000000000000"

  server:
    admin: 
      id: "0000000000000000000"
      channel:
        logs: "0000000000000000000"
        testing: "0000000000000000000"
    community:
      id: "0000000000000000000"
      channel:
        announcements: "0000000000000000000"
        changelogs: "0000000000000000000"
        giveaways: "0000000000000000000"
        tickets: "0000000000000000000"
  
  user:
    my_friends_username: "0000000000000000000"
